name: feature-pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python 3.10.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.9'
     
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install

    - name: Debug Environment Variables
      run: env

    - name: Execute python workflows from bash script
      env: 
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        
      run: |
        poetry run jupyter nbconvert --to notebook --execute notebooks/12_feature_pipeline.ipynb

      
