name: hourly-taxi-demand-inference-pipeline

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python 3.10.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.9'
     
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install
      
     
    - name: Execute python workflows from bash script
      env: 
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: poetry run jupyter nbconvert --to notebook --execute notebooks/14_inference_pipeline.ipynb



      
